title: Solid 7.CSS
description: SolidJS Components for Windows 7 UI
theme: minima
baseurl: "/solid7"
url: "https://your-username.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - COMPONENTS.md
  - EXAMPLES.md

navigation:
  - title: Home
    url: /
  - title: Components
    url: /COMPONENTS
  - title: Examples  
    url: /EXAMPLES
  - title: GitHub
    url: https://github.com/your-username/solid7